### ISSUE TITLE
Server: request logging not happening when errors occurz

### ISSUE THREAD

**Issue by microcreators** [turtl/tracker#141]
Would love to have IP indicated next to errors in the log. Especially true for auth errors, so that I could fight back and ban / zipbomb abusers out there ;) 
All I see today is `error: tres.err -- (uid null): bad login: (bad auth)`

**Comment by orthecreedence** [comment]
Yeah, you're right, the request logging doesn't happen when there's an error response. Weird.

**Comment by orthecreedence** [comment]
Fixed!

**Comment by microcreators** [comment]
Hmmm... Running a clone from this morning and still getting
`error: tres.err -- (uid null): bad login: (bad auth)`

**Comment by orthecreedence** [comment]
Yes, you will get the same error, but the line directly below it will have your IP:

```
error: tres.err -- (uid null): bad login: (bad auth)
info: ::ffff:127.0.0.1 "POST /auth" 403 45
```

**Comment by microcreators** [comment]
That may not help as IDS soft like fail2ban parse log lines in search of abuses and IPs. But thank you. I think I'll get turtle+nginx combo and work on web server logs instead.
