### ISSUE TITLE
Cannot log back after sync issue

### ISSUE THREAD

**Issue by drumjoss** [turtl/tracker#367]
Hello, 

I was logged onto my Ubuntu Laptop but at some point Turtl had a sync problem, unfortunately I did not take a screenshot.

I had to logout and when trying to log back I systematically fall in "Bad Login".

Can you please confirm this is not a corrupted challenge file or similar issue?

I can eventually supply a log file.

Thanks in advance and have a nice day,

Jocelyn

**Comment by ehvs** [comment]
I'm hitting the same issue.
* You really should make more visible the statement that you do not reset the password. If I lose it, how do I capture back my notes?!

**Comment by nerd190** [comment]
Similar issue here, i am always logged in, i opened my phone and i was logged out, now i am unable to sign in: "log in: turtl auth timed out"

**Comment by drumjoss** [comment]
Hello everyone,

Some news: I just created a new account because I really need the app, same thing: I still cannot log into my newly created account with the ubuntu app: Kubuntu 18.04, even after uninstall/re-install with turtl-0.7.2.5-linux64 script.

Have a nice day

**Comment by orthecreedence** [comment]
This should be fixed.

**Comment by drumjoss** [comment]
@orthecreedence Apparently not, I still cannot login with my new and old account.
